#pragma once

#define ID_BTN_SETTINGS 01
#define ID_BTN_RECORDING 02
#define ID_BTN_RECSTOP 03
#define ID_TB_PATH 11
#define ID_TB_DEVICE 13
#define ID_CB_RESOLUTION 12
#define ID_CB_FPS 14
#define ID_CB_SOUND 15
#define ID_BTN_SAVE_SETTINGS 16
#define ID_BTN_CANCEL_SETTINGS 17