/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-112507-ga4877f1ec1-20231024"
#endif /* AVUTIL_FFVERSION_H */
